import { formatReport } from '../src/reporters/index.js';
import type { AuditReport, DetectorResult } from '../src/types.js';

// Box-drawing characters emitted by the terminal reporter.
const BOX_TOP_LEFT = '\u250c';
const BOX_TOP_RIGHT = '\u2510';
const BOX_BOTTOM_LEFT = '\u2514';
const BOX_BOTTOM_RIGHT = '\u2518';
const BOX_HORIZONTAL = '\u2500';
const BOX_VERTICAL = '\u2502';

/** Build a minimal but realistic AuditReport for use in tests. */
function buildMockReport(overrides?: Partial<AuditReport>): AuditReport {
  const detectorResults: DetectorResult[] = [
    {
      detectorId: 'contradictions',
      severity: 'error',
      message: 'Conflict: "always use tabs" vs "always use spaces"',
      line: 12,
      section: 'Code Style',
      suggestion: 'Remove one of the conflicting rules.',
    },
    {
      detectorId: 'vagueness',
      severity: 'warning',
      message: 'Vague term detected: "good code"',
      line: 27,
      section: 'General',
      suggestion: 'Replace "good code" with a concrete criterion.',
    },
    {
      detectorId: 'completeness',
      severity: 'info',
      message: 'No error-handling section found.',
    },
  ];

  return {
    config: {
      filePath: '/project/CLAUDE.md',
      format: 'markdown',
      lineCount: 120,
      tokenEstimate: 1400,
    },
    score: 72,
    detectorResults,
    metrics: {
      lineCount: 120,
      tokenEstimate: 1400,
      sectionCount: 6,
      ruleCount: 18,
      avgRulesPerSection: 3,
      maxSectionLength: 35,
      emptySections: 1,
    },
    timestamp: '2026-03-19T00:00:00.000Z',
    ...overrides,
  };
}

describe('formatReport – json', () => {
  const report = buildMockReport();
  const output = formatReport(report, 'json');
  let parsed: AuditReport;

  it('returns valid JSON', () => {
    expect(() => {
      parsed = JSON.parse(output) as AuditReport;
    }).not.toThrow();
  });

  it('contains the score at the top level', () => {
    parsed = JSON.parse(output) as AuditReport;
    expect(parsed.score).toBe(72);
  });

  it('contains all metrics fields', () => {
    parsed = JSON.parse(output) as AuditReport;
    expect(parsed.metrics).toMatchObject({
      lineCount: 120,
      tokenEstimate: 1400,
      sectionCount: 6,
      ruleCount: 18,
      avgRulesPerSection: 3,
      maxSectionLength: 35,
      emptySections: 1,
    });
  });

  it('contains the detector results array with correct length', () => {
    parsed = JSON.parse(output) as AuditReport;
    expect(Array.isArray(parsed.detectorResults)).toBe(true);
    expect(parsed.detectorResults).toHaveLength(3);
  });

  it('preserves detector severities', () => {
    parsed = JSON.parse(output) as AuditReport;
    const severities = parsed.detectorResults.map((r) => r.severity);
    expect(severities).toContain('error');
    expect(severities).toContain('warning');
    expect(severities).toContain('info');
  });

  it('preserves config metadata', () => {
    parsed = JSON.parse(output) as AuditReport;
    expect(parsed.config.filePath).toBe('/project/CLAUDE.md');
    expect(parsed.config.format).toBe('markdown');
  });
});

describe('formatReport – markdown', () => {
  const report = buildMockReport();
  const output = formatReport(report, 'markdown');

  it('contains a top-level h1 heading', () => {
    expect(output).toMatch(/^# /m);
  });

  it('contains an h2 Findings heading', () => {
    expect(output).toMatch(/^## Findings/m);
  });

  it('contains an h2 Metrics heading', () => {
    expect(output).toMatch(/^## Metrics/m);
  });

  it('includes the score in bold', () => {
    expect(output).toContain('**Score: 72/100**');
  });

  it('includes a markdown table header row for findings', () => {
    expect(output).toContain('| Severity | Message | Line | Suggestion |');
  });

  it('includes table rows for each detector result', () => {
    // Three detector results → three data rows after the header.
    const rows = output
      .split('\n')
      .filter((l) => l.startsWith('| ') && !l.startsWith('| Severity') && !l.startsWith('| ---'));
    expect(rows.length).toBeGreaterThanOrEqual(3);
  });

  it('includes all metrics values', () => {
    expect(output).toContain('120');   // lineCount / tokenEstimate
    expect(output).toContain('1400');  // tokenEstimate
    expect(output).toContain('18');    // ruleCount
  });

  it('has a footer generated-by line', () => {
    expect(output).toContain('*Generated by promptbench*');
  });
});

describe('formatReport – terminal', () => {
  const report = buildMockReport();
  const output = formatReport(report, 'terminal');
  // Strip ANSI escape codes so character assertions are colour-agnostic.
  // eslint-disable-next-line no-control-regex
  const plain = output.replace(/\x1B\[[0-9;]*m/g, '');

  it('opens with a top-left box-drawing corner', () => {
    expect(plain).toContain(BOX_TOP_LEFT);
  });

  it('opens with a top-right box-drawing corner', () => {
    expect(plain).toContain(BOX_TOP_RIGHT);
  });

  it('closes with a bottom-left box-drawing corner', () => {
    expect(plain).toContain(BOX_BOTTOM_LEFT);
  });

  it('closes with a bottom-right box-drawing corner', () => {
    expect(plain).toContain(BOX_BOTTOM_RIGHT);
  });

  it('uses horizontal box-drawing lines', () => {
    expect(plain).toContain(BOX_HORIZONTAL);
  });

  it('uses vertical box-drawing lines for side borders', () => {
    expect(plain).toContain(BOX_VERTICAL);
  });

  it('includes the score', () => {
    expect(plain).toContain('72');
  });

  it('includes the file path', () => {
    expect(plain).toContain('/project/CLAUDE.md');
  });

  it('contains a Findings section label', () => {
    expect(plain).toContain('Findings');
  });

  it('contains a Metrics section label', () => {
    expect(plain).toContain('Metrics');
  });

  it('surfaces the error finding message', () => {
    // Message is truncated to fit; check a stable prefix.
    expect(plain).toContain('Conflict:');
  });

  it('surfaces the warning finding message', () => {
    expect(plain).toContain('Vague term detected');
  });

  it('includes a summary line with error/warning/info counts', () => {
    expect(plain).toMatch(/1 errors?, 1 warnings?, 1 info/);
  });

  it('sorts errors before warnings in the output', () => {
    const errorIdx = plain.indexOf('Conflict:');
    const warnIdx = plain.indexOf('Vague term detected');
    expect(errorIdx).toBeGreaterThan(-1);
    expect(warnIdx).toBeGreaterThan(-1);
    expect(errorIdx).toBeLessThan(warnIdx);
  });
});

describe('formatReport – edge cases', () => {
  it('handles a perfect score (100) without crashing', () => {
    const report = buildMockReport({ score: 100, detectorResults: [] });
    const output = formatReport(report, 'terminal');
    // eslint-disable-next-line no-control-regex
    const plain = output.replace(/\x1B\[[0-9;]*m/g, '');
    expect(plain).toContain('100');
    expect(plain).toContain('No issues found');
  });

  it('handles a zero score without crashing', () => {
    const report = buildMockReport({ score: 0 });
    expect(() => formatReport(report, 'terminal')).not.toThrow();
    expect(() => formatReport(report, 'json')).not.toThrow();
    expect(() => formatReport(report, 'markdown')).not.toThrow();
  });

  it('json round-trips the timestamp unchanged', () => {
    const report = buildMockReport({ timestamp: '2026-03-19T12:34:56.000Z' });
    const parsed = JSON.parse(formatReport(report, 'json')) as AuditReport;
    expect(parsed.timestamp).toBe('2026-03-19T12:34:56.000Z');
  });

  it('markdown escapes pipe characters in finding messages', () => {
    const report = buildMockReport({
      detectorResults: [
        {
          detectorId: 'test',
          severity: 'info',
          message: 'Rule A | Rule B',
        },
      ],
    });
    const output = formatReport(report, 'markdown');
    // Pipes inside cell content must be escaped so they don't break the table.
    expect(output).toContain('Rule A \\| Rule B');
  });
});
