import type { AuditReport, DetectorResult } from '../types.js';

/** Pick an emoji based on score thresholds */
function scoreEmoji(score: number): string {
  if (score >= 80) return '\u2705';
  if (score >= 50) return '\u26a0\ufe0f';
  return '\u274c';
}

/** Escape pipe characters for markdown table cells */
function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

/** Format a single finding as a markdown table row */
function findingRow(f: DetectorResult): string {
  const severity = escapeCell(f.severity);
  const message = escapeCell(f.message);
  const line = f.line != null ? String(f.line) : '-';
  const suggestion = f.suggestion ? escapeCell(f.suggestion) : '-';
  return `| ${severity} | ${message} | ${line} | ${suggestion} |`;
}

/**
 * Format an audit report as a markdown document.
 */
export function reportMarkdown(report: AuditReport): string {
  const lines: string[] = [];

  // Title
  lines.push('# Promptbench Audit Report');
  lines.push('');

  // Score
  const emoji = scoreEmoji(report.score);
  lines.push(`**Score: ${report.score}/100** ${emoji}`);
  lines.push('');

  // Findings table
  lines.push('## Findings');
  lines.push('');
  lines.push('| Severity | Message | Line | Suggestion |');
  lines.push('| --- | --- | --- | --- |');

  for (const f of report.detectorResults) {
    lines.push(findingRow(f));
  }

  lines.push('');

  // Metrics
  lines.push('## Metrics');
  lines.push('');
  const m = report.metrics;
  lines.push(`- **Lines:** ${m.lineCount}`);
  lines.push(`- **Token estimate:** ${m.tokenEstimate}`);
  lines.push(`- **Sections:** ${m.sectionCount}`);
  lines.push(`- **Rules:** ${m.ruleCount}`);
  lines.push(`- **Avg rules per section:** ${m.avgRulesPerSection}`);
  lines.push(`- **Max section length:** ${m.maxSectionLength}`);
  lines.push(`- **Empty sections:** ${m.emptySections}`);
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by promptbench*');

  return lines.join('\n');
}
